name: Build

on:
  push:
    branches:
    - master
    - staging
    - develop
    tags:
    - r*
  pull_request:
    branches:
    - master
    - staging
    - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2

      - name: Build
        run:
          make all

      - name: Coveralls
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: coverage/test.cov


  # The "deploy" workflow
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [build] # Only run this workflow when "build" workflow succeeds
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v2

      - name: Build Release
        run:
          make release

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/r')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            p2-linux-arm64
            p2-linux-x86_64
            p2-linux-i386
            p2-windows-i386.exe
            p2-windows-x86_64.exe
            p2-darwin-x86_64
            p2-darwin-i386
            p2-darwin-arm64
            p2-freebsd-x86_64